# IDS LAB (30-Oct-2024)

1. *Create a 1D array of integers from 1 to 20. Reshape it into a 4x5 2D array, then replace all elements in the last column with zeros. Finally, flatten the array back to 1D and print the result.*

In [4]:
import numpy as np

lst = []
for i in range(1,21):
    lst.append(i)
arr = np.array(lst)
arr2 = arr.reshape(4,5)
arr2[:,-1] = 0
final = arr2.flatten()
print(final)

[[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]
[ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


2. *Generate a 2D array of random integers between 10 and 50 with a shape of 5x5. Calculate and print the mean, sum, minimum, and maximum values for each row and each column separately.*

In [ ]:
import numpy as np

