# IDS LAB (30-Oct-2024)

**1. *Create a 1D array of integers from 1 to 20. Reshape it into a 4x5 2D array, then replace all elements in the last column with zeros. Finally, flatten the array back to 1D and print the result.***

In [4]:
import numpy as np

lst = []
for i in range(1,21):
    lst.append(i)
arr = np.array(lst)
arr2 = arr.reshape(4,5)
arr2[:,-1] = 0
final = arr2.flatten()
print("Final Matrix: \n",final)

Final Matrix: 
 [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


**2. *Generate a 2D array of random integers between 10 and 50 with a shape of 5x5. Calculate and print the mean, sum, minimum, and maximum values for each row and each column separately.***

In [2]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(10,51,size=(5,5))
print("2D Array: \n",arr)

print("Rows Sum: ", np.sum(arr,axis = 1))
print("Rows Mean: ", np.mean(arr,axis = 1))
print("Rows Min: ", np.min(arr,axis = 1))
print("Rows Max: ", np.max(arr,axis = 1))

print("Cols Sum: ", np.sum(arr,axis = 0))
print("Cols Mean: ", np.mean(arr,axis = 0))
print("Cols Min: ", np.min(arr,axis = 0))
print("Cols Max: ", np.max(arr,axis = 0))

2D Array:  [[10 13 13 49 19]
 [29 31 46 33 16]
 [34 34 22 11 48]
 [49 33 34 27 47]
 [35 23 18 19 30]]
Rows Sum:  [104 155 149 190 125]
Rows Mean:  [20.8 31.  29.8 38.  25. ]
Rows Min:  [10 16 11 27 18]
Rows Max:  [49 46 48 49 35]
Cols Sum:  [157 134 133 139 160]
Cols Mean:  [31.4 26.8 26.6 27.8 32. ]
Cols Min:  [10 13 13 11 16]
Cols Max:  [49 34 46 49 48]


**3. *Create an identity matrix of size 4x4. Add a constant (e.g., 5) to each element in the diagonal, and then replace the last row with a row of ones. Print the final matrix.***

In [5]:
import numpy as np

mat = np.identity(4)
print("Identity Matrix: \n", mat)
np.fill_diagonal(mat,np.diagonal(mat)+5)
print("Updated Matrix: \n", mat)
mat[-1,:]=1
print("Final Matrix: \n", mat)

Identity Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Updated Matrix: 
 [[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 6.]]
Final Matrix: 
 [[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


**4. *Generate a 1D array of 15 random integers between 0 and 20. Count and display the number of occurrences of each unique value in the array, and list the indices of elements greater than 10.***

In [8]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(0,21,size=15)
print("Array: \n",arr)

unique, counts = np.unique(arr,return_counts=True)
print("Count of unique values")
for val,count in zip(unique, counts):
    print(f"{val}: {count}")

ind = np.where(arr>10)[0]
print("Indices for >10: ", ind)


Array: 
 [12 15  0  3  3  7  9 19 18  4  6 12  1  6  7]
Count of unique values
0: 1
1: 1
3: 2
4: 1
6: 2
7: 2
9: 1
12: 2
15: 1
18: 1
19: 1
Indices for >10:  [ 0  1  7  8 11]
