# IDS LAB (06-Nov-2024)

## Task 1:
### Scenario: *You are managing game scores for a gaming application.*

**1. Create a NumPy array to store player names, game scores, and levels reached.**

In [1]:
import numpy as np

player_data = np.array([
    ["Ali", 1000, 5],
    ["Haris", 800, 4],
    ["Talha", 1200, 6],
    ["Durrab", 900, 5],
    ["Saad", 700, 3]
], dtype=object)

print("Initial Player Data:")
print(player_data)


Initial Player Data:
[['Ali' 1000 5]
 ['Haris' 800 4]
 ['Talha' 1200 6]
 ['Durrab' 900 5]
 ['Saad' 700 3]]


**2. Update the score of the player who has reached the highest level.**

In [2]:
max_level_index = np.argmax(player_data[:, 2])
player_data[max_level_index, 1] += 100

print("Updated Player Data After Score Update:")
print(player_data)


Updated Player Data After Score Update:
[['Ali' 1000 5]
 ['Haris' 800 4]
 ['Talha' 1300 6]
 ['Durrab' 900 5]
 ['Saad' 700 3]]


**3. Append a new player's data (name, score, level) to the array.**

In [3]:
new_player = np.array([["Rehan", 1100, 6]], dtype=object)
player_data = np.vstack((player_data, new_player))

print("Updated Player Data After Adding New Player:")
print(player_data)


Updated Player Data After Adding New Player:
[['Ali' 1000 5]
 ['Haris' 800 4]
 ['Talha' 1300 6]
 ['Durrab' 900 5]
 ['Saad' 700 3]
 ['Rehan' 1100 6]]


**4. Insert a new player's score at a specific index within the array.**

In [4]:
new_player = np.array([["Affan", 1000, 5]], dtype=object)
player_data = np.insert(player_data, 2, new_player, axis=0)

print("\nUpdated Player Data After Inserting New Player:")
print(player_data)


Updated Player Data After Inserting New Player:
[['Ali' 1000 5]
 ['Haris' 800 4]
 ['Affan' 1000 5]
 ['Talha' 1300 6]
 ['Durrab' 900 5]
 ['Saad' 700 3]
 ['Rehan' 1100 6]]


**5. Delete the player with the lowest score from the dataset.**

In [5]:
min_score_index = np.argmin(player_data[:, 1])
player_data = np.delete(player_data, min_score_index, axis=0)

print("\nUpdated Player Data After Deleting Player with Lowest Score:")
print(player_data)


Updated Player Data After Deleting Player with Lowest Score:
[['Ali' 1000 5]
 ['Haris' 800 4]
 ['Affan' 1000 5]
 ['Talha' 1300 6]
 ['Durrab' 900 5]
 ['Rehan' 1100 6]]


## Task 2:
### Scenario: *You are analyzing website traffic data.*

**1. Create two NumPy arrays: one for daily visitors and another for pages viewed.**

In [6]:
daily_visitors = np.array([100, 120, 150, 180, 200, 250, 300])
pages_viewed = np.array([50, 60, 70, 80, 100, 120, 150])

print("Daily Visitors:\n", daily_visitors)
print()
print("Pages Viewed:\n", pages_viewed)

Daily Visitors:
 [100 120 150 180 200 250 300]

Pages Viewed:
 [ 50  60  70  80 100 120 150]


**2. Create a shallow copy of the visitors array and a deep copy of the pages viewed array.**

In [13]:
visitors_copy = daily_visitors
pages_copy = pages_viewed.copy()

print("Visitors Copy (Shallow):\n", visitors_copy)
print()
print("Pages Copy (Deep):\n", pages_copy)

Visitors Copy (Shallow):
 [500 120 150 180 200 250 300]

Pages Copy (Deep):
 [200  60  70  80 100 120 150]


**3. Concatenate both arrays to form a new array.**

In [8]:
traffic_data = np.stack((daily_visitors, pages_viewed), axis=1)

print("Concatenated Traffic Data:")
print(traffic_data)

Concatenated Traffic Data:
[[100  50]
 [120  60]
 [150  70]
 [180  80]
 [200 100]
 [250 120]
 [300 150]]


**4. Split the concatenated array into two parts based on a threshold (e.g., more than 100 pages viewed).**

In [9]:
threshold = 100
high_traffic = traffic_data[traffic_data[:, 1] > threshold]
low_traffic = traffic_data[traffic_data[:, 1] <= threshold]

print("\nHigh Traffic (>100 pages viewed):")
print(high_traffic)
print("\nLow Traffic (<=100 pages viewed):")
print(low_traffic)


High Traffic (>100 pages viewed):
[[250 120]
 [300 150]]

Low Traffic (<=100 pages viewed):
[[100  50]
 [120  60]
 [150  70]
 [180  80]
 [200 100]]


**5. Modify the original arrays and observe the changes in the copies.**

In [14]:
daily_visitors[0] = 500
pages_viewed[0] = 200

print("\nModified Daily Visitors:")
print(daily_visitors)
print("\nModified Pages Viewed:")
print(pages_viewed)
print("\nVisitors Copy After Modification:")
print(visitors_copy)
print("\nPages Copy After Modification:")
print(pages_copy)


Modified Daily Visitors:
[500 120 150 180 200 250 300]

Modified Pages Viewed:
[200  60  70  80 100 120 150]

Visitors Copy After Modification:
[500 120 150 180 200 250 300]

Pages Copy After Modification:
[200  60  70  80 100 120 150]
